
platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'WSSProgressHUD_Example' do
  pod 'WSSProgressHUD', :path => '../'

  target 'WSSProgressHUD_Tests' do
    inherit! :search_paths

    
  end
end
